
<?php
require_once('loginController.php')

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>complete responsive adventure & tour website design</title>

    <!-- font awesome cdn link  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css" />

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">


    <!-- Customized Bootstrap Stylesheet -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- custom css file link  -->
    <link rel="stylesheet" href="style.css">
</head>
<body>
<!-- header section starts  -->
<header class="header">
    <a href="#" class="logo"> <i class="fas fa-users"></i> Group collaboration. </a>
    <nav class="navbar">
        <div id="nav-close" class="fas fa-times"></div>
        <a href="home.php">Home</a>
        <a href="index.php">About</a>
        <?php if(!isset($_SESSION['login'])) :?>
            <a href="Register.php">Register</a>
            <a href="Login.php">Login</a>
            <script>
                document.write("<a href='#' onClick='alert(\"You need to login or register first\")'>Adding post</a>");
            </script>
        <?php elseif(isset($_SESSION['login'])) :?>
            <a href="UserProfileController.php">Profile</a>
            <a href="#chat">Chat</a>
            <a href="Post.php">Adding post</a>
            <form method="post" action="">
                <button type="submit" name="logout" class="logout-btn"><i class="fas fa-sign-out-alt"></i></button>
            </form>
        <?php endif;?>
    </nav>
    <div class="icons">
        <div id="menu-btn" class="fas fa-bars"></div>
        <div id="search-btn" class="fas fa-search"></div>
    </div>
</header>

<!-- search form  -->
<div class="search-form">
    <div id="close-search" class="fas fa-times"></div>
    <form action="">
        <input type="search" name="" placeholder="search here..." id="search-box">
        <label for="search-box" class="fas fa-search"></label>
    </form>
</div>
<!-- header section ends -->

</body>
</html>