<?php
require('Templete/navbar.phtml')?>

<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

<div class="container">
        <div class="col-md-8 col-md-offset-2">
            <h1>Create post</h1>
            <form action="Post.php" method="POST" class="post-form">
                <div class="form-group">
                    <label for="title">Title <span class="require">*</span></label>
                    <input type="text"  class="form-control" name="title" onkeyup="removeSpecialChars(this)" />
                </div>
                <div class="form-group">
                    <label for="category">Category</label>
                    <select class="form-control" name="category">
                        <option value="">Select a category</option>
                        <option value="Sports">Sports</option>
                        <option value="Business">Business</option>
                        <option value="Gaming">Gaming</option>
                        <option value="Software Development">Software Development</option>
                        <option value="Marketing">Marketing</option>
                        <option value="Music">Music</option>
                        <option value="Entertainment">Entertainment</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="content">Content</label>
                    <textarea  rows="5"  class="form-control" name="content" onkeyup="removeSpecialChars(this)" ></textarea>
                </div>
                <div class="form-group">
                    <p><span class="require">*</span> - required fields</p>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary" name="submit" >
                        Create
                    </button>
                    <button class="btn btn-default">
                        Cancel
                    </button>
                </div>
            </form>
        </div>
    </div>
<?php
require('Templete/footer.phtml')?>
